#!/bin/bash

# Preparing input
if [ "$1" ]; then
    MODE="$(tr [A-Z] [a-z] <<< "$1")"
else
    # use random value to trigger help
    MODE="help"
fi
if [ "$2" ]; then
    COMMAND="$(tr [A-Z] [a-z] <<< "$2")"
else
    # use random value to trigger help
    COMMAND=""
fi

# Calling the right service based on PHP and Composer presence
printf "Checking PHP and composer..."
php --version && composer --version
if  [ $? -eq 0 ]; then
    if [ -d "./vendor" ] && [ -f "./.env" ]; then
        ./caligrafer.php $MODE $COMMAND
    elif [ -d "./vendor" ]; then
        printf "\n\nCaligrafy needs to be initialized first\n\n"
        ./caligrafer.php initialize
        ./caligrafer.php $MODE $COMMAND
    else
        printf "\n\nIt seems that you have downloaded Caligrafy directly from Github.\nLet's get the dependencies first...\n\n"
        composer install
        ./caligrafer.php initialize
        ./caligrafer.php $MODE $COMMAND
    fi
else
    ./.bin/server $COMMAND
fi