#!/bin/bash

# Preparing input
if [ "$1" ]; then
    MODE="$(tr [A-Z] [a-z] <<< "$1")"
else
    # use random value to trigger help
    MODE="help"
fi
if [ "$2" ]; then
    COMMAND="$(tr [A-Z] [a-z] <<< "$2")"
else
    # use random value to trigger help
    COMMAND="help"
fi

# Calling the right service based on PHP and Composer presence
printf "Checking PHP and composer..."
php --version && composer --version
if  [ $? -eq 0 ]; then
    ./caligrafer.php $MODE $COMMAND
else
    ./.bin/server $COMMAND
fi